replicaCount: 1

image:
  repository: jc21/nginx-proxy-manager
  tag: v2.12.6
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: NodePort   # Change to LoadBalancer if in cloud
  ports:
    http: 80
    https: 443
    admin: 81

persistence:
  enabled: true
  size: 500Mi
