apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-wp-config-php-init
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  wp-config.php: |-
    <?php
    /**
    * The base configuration for WordPress
    *
    * The wp-config.php creation script uses this file during the installation.
    * You don't have to use the website, you can copy this file to "wp-config.php"
    * and fill in the values.
    *
    * This file contains the following configurations:
    *
    * * Database settings
    * * Secret keys
    * * Database table prefix
    * * ABSPATH
    *
    * @link https://developer.wordpress.org/advanced-administration/wordpress/wp-config/
    *
    * @package WordPress
    */

    // ** Database settings - You can get this info from your web host ** //
    /** The name of the database for WordPress */
    define( 'DB_NAME', 'wordpress' );

    /** Database username */
    define( 'DB_USER', 'andy' );

    /** Database password */
    define( 'DB_PASSWORD', getenv('MYSQL_PASS') );

    /** Database hostname */
    define( 'DB_HOST', 'wordpress-stack-mysql:3306' );

    /** Database charset to use in creating database tables. */
    define( 'DB_CHARSET', 'utf8' );

    /** The database collate type. Don't change this if in doubt. */
    define( 'DB_COLLATE', '' );

    /**#@+
    * Authentication unique keys and salts.
    *
    * Change these to different unique phrases! You can generate these using
    * the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}.
    *
    * You can change these at any point in time to invalidate all existing cookies.
    * This will force all users to have to log in again.
    *
    * @since 2.6.0
    */
    define( 'AUTH_KEY',         'qK}$ym3Rh;xfP~E o!gzdm.ZD,}{k+wA$1g:w7Ar ]i9v)Ud/TN7wcH=>V2Qs}Cj' );
    define( 'SECURE_AUTH_KEY',  'V?5M WY[_T}3A)SzQCryXd?3Wbt#tW7A8tU~@Ok}WOorqF0`87*EG<3IDPaA522x' );
    define( 'LOGGED_IN_KEY',    '0CTSfR5n}H$O*@#1[-+UkJ6kTWRT}`K#+[-^_8/ f66M1aSE^oV3u?t}Qv08SbA(' );
    define( 'NONCE_KEY',        '_VI`=:Hw#AJKS*q`2t[:<!JH*gN_??!`9So8Su_b$*vuH9iEcZbNiB~X1C!LqjjG' );
    define( 'AUTH_SALT',        '?0Et5 PyGwi6Misc%[@,~<GDU[,:DTr!swNDVT*`jXIqpRR8Cu`bI[xB!BO!{?Y|' );
    define( 'SECURE_AUTH_SALT', 'm]zZ-i?c;yPn|&{o?O3g$n]vuv!?pvg}!1-jxI$S*R5qP|HneDR: j$]k;qw/v*g' );
    define( 'LOGGED_IN_SALT',   '$Q+/VPyX%YGUaDWM -#fPx%aBim)KnYe9BRs5zwg[)w/U7!`0#RG*-4AC.na8&BB' );
    define( 'NONCE_SALT',       'lU[dE/B21$*8?a!oM@>v)3W${q-yr9K.vT6wlT{EP K:@3<t|}J{_%W:?*b1z*}Q' );

    /**#@-*/

    /**
    * WordPress database table prefix.
    *
    * You can have multiple installations in one database if you give each
    * a unique prefix. Only numbers, letters, and underscores please!
    *
    * At the installation time, database tables are created with the specified prefix.
    * Changing this value after WordPress is installed will make your site think
    * it has not been installed.
    *
    * @link https://developer.wordpress.org/advanced-administration/wordpress/wp-config/#table-prefix
    */
    $table_prefix = 'wp_';

    /**
    * For developers: WordPress debugging mode.
    *
    * Change this to true to enable the display of notices during development.
    * It is strongly recommended that plugin and theme developers use WP_DEBUG
    * in their development environments.
    *
    * For information on other constants that can be used for debugging,
    * visit the documentation.
    *
    * @link https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/
    */
    define( 'WP_DEBUG', false );

    /* Add any custom values between this line and the "stop editing" line. */



    define( 'FS_METHOD', 'direct' );
    /**
    * The WP_SITEURL and WP_HOME options are configured to access from any hostname or IP address.
    * If you want to access only from an specific domain, you can modify them. For example:
    *  define('WP_HOME','http://example.com');
    *  define('WP_SITEURL','http://example.com');
    *
    */
    if (
        (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ||
        (!empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on')
    ) {
        $_SERVER['HTTPS'] = 'on';
    }

    // Fix host when behind ingress reverse proxy
    if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
        $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
    }

    define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] );
    define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] );
    /* That's all, stop editing! Happy publishing. */

    /** Absolute path to the WordPress directory. */
    if ( ! defined( 'ABSPATH' ) ) {
      define( 'ABSPATH', __DIR__ . '/' );
    }

    /** Sets up WordPress vars and included files. */
    require_once ABSPATH . 'wp-settings.php';

    /**
    * Disable pingback.ping xmlrpc method to prevent WordPress from participating in DDoS attacks
    * More info at: https://docs.bitnami.com/general/apps/wordpress/troubleshooting/xmlrpc-and-pingback/
    */
    if ( !defined( 'WP_CLI' ) ) {
      // remove x-pingback HTTP header
      add_filter("wp_headers", function($headers) {
        unset($headers["X-Pingback"]);
        return $headers;
      });
      // disable pingbacks
      add_filter( "xmlrpc_methods", function( $methods ) {
        unset( $methods["pingback.ping"] );
        return $methods;
      });
    }
