apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-proxy-manager
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: 80
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: 443
    - name: admin
      port: {{ .Values.service.ports.admin }}
      targetPort: 81
